import { go } from './main.js'
import { projects, makeProject, saveProject } from './store.js'

const HISTORY_KEY='king-motion-ai-history-v1'
const styles=['Realistic','Cinematic','Anime','Digital Art','Studio Portrait','Product','Fantasy','Dark Edit Asset','Transparent Character Asset']
const actions=['Remove Background','Transparent Cutout','Clean Background','Replace Background','Enhance Subject','Create PNG-style Asset','Posterize','Add Dramatic Light','Stylize','Create Alternate Version']
const examples={create:['Create a cinematic masked character with transparent background','Generate a dramatic anime-style fighter with dark lighting','Create a realistic hero portrait for a video edit','Create a clean PNG-style subject with no background'],edit:['Remove the background and keep only the character','Turn this into a dramatic edit asset','Enhance lighting and isolate the subject','Replace the background with a dark cinematic look']}
const safeHistory=()=>{try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const fileData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})

export function aiStudio(root){
 const query=new URLSearchParams(location.search),context={projectId:query.get('project'),layerId:query.get('layer'),action:query.get('action')};
 const state={mode:context.action==='edit'||context.action==='remove-background'?'edit':'create',prompt:context.action==='remove-background'?'Remove the background and keep only the subject. Return a transparent image when supported.':'',source:null,result:null,loading:false,error:'',ratio:'1:1',style:'Cinematic',quality:'High',transparent:context.action==='remove-background',variations:1,history:safeHistory(),compare:false};
 const draw=()=>{root.innerHTML=`<main class="ai-studio"><header class="ai-top"><button data-back aria-label="Back">←</button><span class="ai-mark">✦</span><div><b>AI Image Studio</b><small>GENERATIVE ASSET LAB</small></div><button data-history>History <em>${state.history.length}</em></button><button class="primary" data-new>＋ New</button></header><div class="ai-layout"><aside class="ai-panel input-panel"><div class="mode-tabs"><button data-mode="create" class="${state.mode==='create'?'active':''}">Create</button><button data-mode="edit" class="${state.mode==='edit'?'active':''}">Edit</button></div>${state.mode==='edit'?uploadMarkup(state):''}<label class="prompt-label"><span>${state.mode==='create'?'Describe your image':'Describe the edit'}</span><textarea id="ai-prompt" maxlength="2000" placeholder="${state.mode==='create'?'A cinematic hero portrait…':'Remove the background…'}">${escape(state.prompt)}</textarea><small>${state.prompt.length}/2000</small></label><div class="suggestions"><b>TRY A PROMPT</b>${examples[state.mode].map(x=>`<button data-prompt="${escape(x)}">${escape(x)}</button>`).join('')}</div><button class="primary generate" data-generate ${state.loading?'disabled':''}>${state.loading?'Generating…':state.mode==='create'?'✦ Generate Image':'✦ Generate Edit'}</button></aside><section class="ai-preview ${state.loading?'loading':''}">${previewMarkup(state)}</section><aside class="ai-panel settings-panel"><section><small>VISUAL LANGUAGE</small><h3>Style</h3><div class="chips styles">${styles.map(x=>`<button data-style="${x}" class="${state.style===x?'active':''}">${x}</button>`).join('')}</div></section><section><h3>Aspect ratio</h3><div class="ratio-list">${['1:1','9:16','16:9','4:5','3:4'].map(x=>`<button data-ratio="${x}" class="${state.ratio===x?'active':''}">${x}</button>`).join('')}</div></section><section class="setting-row"><label>Quality<select data-quality><option>Standard</option><option ${state.quality==='High'?'selected':''}>High</option></select></label><label>Variations<select data-variations><option>1</option><option>2</option><option>4</option></select></label></section><label class="toggle"><input data-transparent type="checkbox" ${state.transparent?'checked':''}><i></i><span>Transparent background<small>Best effort — verify the result before use.</small></span></label><section><small>QUICK ACTIONS</small><h3>Asset workflows</h3><div class="chips quick">${actions.map(x=>`<button data-action="${x}">${x}</button>`).join('')}</div></section></aside></div><div class="ai-mobile-action"><button data-settings>Controls</button><button class="primary" data-generate>${state.loading?'Generating…':state.mode==='create'?'Generate Image':'Generate Edit'}</button></div>${historyMarkup(state)}</main>`;bind()}
 const bind=()=>{
  root.querySelector('[data-back]').onclick=()=>context.projectId?go(`/editor?id=${context.projectId}`):go('/');
  root.querySelector('[data-new]').onclick=()=>{state.prompt='';state.source=null;state.result=null;state.error='';draw()};
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.error='';draw()});
  root.querySelector('#ai-prompt').oninput=e=>{state.prompt=e.target.value;root.querySelector('.prompt-label small').textContent=`${e.target.value.length}/2000`};
  root.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{state.prompt=b.dataset.prompt;draw()});
  root.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{state.style=b.dataset.style;draw()});root.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{state.ratio=b.dataset.ratio;draw()});
  root.querySelector('[data-quality]').onchange=e=>state.quality=e.target.value;root.querySelector('[data-variations]').onchange=e=>state.variations=+e.target.value;root.querySelector('[data-transparent]').onchange=e=>state.transparent=e.target.checked;
  root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{state.mode='edit';state.prompt=actionPrompt(b.dataset.action);state.transparent=/Background|Cutout|PNG/.test(b.dataset.action);draw()});
  root.querySelectorAll('[data-generate]').forEach(b=>b.onclick=generate);root.querySelector('[data-settings]')?.addEventListener('click',()=>root.querySelector('.settings-panel').classList.toggle('mobile-open'));
  const input=root.querySelector('#source-file');if(input)input.onchange=e=>acceptFile(e.target.files[0]);const drop=root.querySelector('.upload-zone');if(drop){drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');acceptFile(e.dataTransfer.files[0])};root.querySelector('[data-clear-source]')?.addEventListener('click',()=>{state.source=null;draw()})}
  root.querySelector('[data-history]').onclick=()=>root.querySelector('.history-drawer').classList.add('open');root.querySelector('[data-close-history]').onclick=()=>root.querySelector('.history-drawer').classList.remove('open');
  root.querySelectorAll('[data-reuse]').forEach(b=>b.onclick=()=>{const h=state.history.find(x=>x.id===b.dataset.reuse);state.mode=h.mode;state.prompt=h.prompt;state.result=h.result||null;draw()});root.querySelectorAll('[data-delete-history]').forEach(b=>b.onclick=()=>{state.history=state.history.filter(x=>x.id!==b.dataset.deleteHistory);persist();draw()});
  root.querySelector('[data-download]')?.addEventListener('click',download);root.querySelector('[data-insert]')?.addEventListener('click',()=>handoff(false));root.querySelector('[data-replace]')?.addEventListener('click',()=>handoff(true));root.querySelector('[data-compare]')?.addEventListener('click',()=>{state.compare=!state.compare;draw()})
 }
 const acceptFile=async file=>{if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type))return showError('Choose a PNG, JPEG, or WebP image.');if(file.size>10*1024*1024)return showError('The source image must be smaller than 10 MB.');state.source={name:file.name,mime:file.type,data:await fileData(file)};state.error='';draw()}
 const generate=async()=>{state.prompt=root.querySelector('#ai-prompt')?.value.trim()||state.prompt.trim();if(!state.prompt)return showError('Describe what you want to create first.');if(state.mode==='edit'&&!state.source)return showError('Upload an image to edit with AI.');state.loading=true;state.error='';draw();try{const payload={prompt:state.prompt,style:state.style,aspectRatio:state.ratio,quality:state.quality,transparentBackground:state.transparent,variations:state.variations,...(state.source&&{image:{mimeType:state.source.mime,data:state.source.data.split(',')[1]}})};const response=await fetch(`/api/ai/image/${state.mode}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||friendlyStatus(response.status));if(!body.images?.[0]?.data)throw new Error('Gemini returned no usable image. Try refining the prompt.');state.result=`data:${body.images[0].mimeType||'image/png'};base64,${body.images[0].data}`;state.history.unshift({id:crypto.randomUUID(),mode:state.mode,prompt:state.prompt,timestamp:Date.now(),result:state.result});state.history=state.history.slice(0,8);persist()}catch(e){state.error=e.message||'Generation failed. Please try again.'}finally{state.loading=false;draw()}}
 const persist=()=>{try{localStorage.setItem(HISTORY_KEY,JSON.stringify(state.history))}catch{try{localStorage.setItem(HISTORY_KEY,JSON.stringify(state.history.map(({result,...x})=>x)))}catch{}}}
 const showError=message=>{state.error=message;draw()};const download=()=>{const a=document.createElement('a');a.href=state.result;a.download=`king-motion-ai-${Date.now()}.png`;a.click()};
 const handoff=replace=>{if(!state.result)return;let project=projects().find(x=>x.id===context.projectId);if(!project){project=makeProject({name:'AI Image Composition'});saveProject(project)}sessionStorage.setItem('king-motion-ai-handoff',JSON.stringify({projectId:project.id,layerId:replace?context.layerId:null,data:state.result,prompt:state.prompt}));go(`/editor?id=${project.id}`)}
 draw()
}
function uploadMarkup(s){return `<div class="upload-zone"><input id="source-file" type="file" accept="image/png,image/jpeg,image/webp">${s.source?`<img src="${s.source.data}" alt="Source preview"><div><b>${escape(s.source.name)}</b><button data-clear-source>Clear</button></div>`:`<div class="upload-icon">⇧</div><b>Upload an image to edit with AI</b><span>Drop PNG, JPEG or WebP · max 10 MB</span><label for="source-file">Choose image</label>`}</div>`}
function previewMarkup(s){if(s.loading)return `<div class="ai-loader"><i></i><span>Gemini is shaping your pixels</span><small>Generating a new visual asset…</small></div>`;if(s.error)return `<div class="ai-empty error"><b>Generation paused</b><p>${escape(s.error)}</p><button data-generate>Try again</button></div>`;if(s.result)return `<div class="result-frame ${s.compare?'compare':''}">${s.compare&&s.source?`<img src="${s.source.data}" alt="Original">`:''}<img src="${s.result}" alt="AI generated result"></div><div class="result-actions"><button data-download>↓ Download</button>${s.source?'<button data-compare>◐ Before / After</button>':''}<button class="primary" data-insert>${location.search?'Insert at Playhead':'Insert into Project'}</button>${s.source?'<button data-replace>Replace Selected Layer</button>':''}</div>`;return `<div class="ai-empty"><div class="procedural-orb"><i></i><b>✦</b></div><small>AI CANVAS · ${s.ratio}</small><h2>${s.mode==='create'?'Imagine the first frame.':'Transform an existing asset.'}</h2><p>${s.mode==='create'?'Describe a subject, mood, lighting and visual style.':'Upload an image, choose a quick workflow, and direct the change.'}</p></div>`}
function historyMarkup(s){return `<aside class="history-drawer"><header><div><small>LOCAL SESSION</small><h2>Generation history</h2></div><button data-close-history>×</button></header>${s.history.length?s.history.map(h=>`<article>${h.result?`<img src="${h.result}" alt="">`:'<i>✦</i>'}<div><b>${escape(h.prompt)}</b><small>${h.mode} · ${new Date(h.timestamp).toLocaleString()}</small><button data-reuse="${h.id}">Reopen / reuse</button><button data-delete-history="${h.id}">Delete</button></div></article>`).join(''):'<p>Your latest creations will stay on this device when browser storage allows.</p>'}</aside>`}
const actionPrompt=x=>({"Remove Background":'Remove the background and keep only the main subject. Return transparency if supported.',"Transparent Cutout":'Create a clean transparent cutout of the main subject with precise edges.',"Clean Background":'Clean and simplify the background while preserving the subject.',"Replace Background":'Replace the background with a dark cinematic environment.',"Enhance Subject":'Enhance subject detail, lighting, and clarity without changing identity.',"Create PNG-style Asset":'Isolate the subject as a clean PNG-style asset on a transparent background.',Posterize:'Create a bold posterized graphic treatment.',"Add Dramatic Light":'Add dramatic cinematic rim light and deep contrast.',Stylize:'Create a striking stylized alternate treatment.',"Create Alternate Version":'Create a distinct alternate version while preserving the core subject.'}[x]||x)
const friendlyStatus=s=>s===429?'The AI service is busy or rate-limited. Wait a moment and retry.':s===413?'The image is too large for this request.':s>=500?'The AI service is temporarily unavailable.':'The request could not be completed.'
