const TITLES={
 effect:['Exposure Punch','Deep Contrast','Cold Steel','Warm Film','Neon Contrast','Blue Night','Golden Light','Matte Black','RGB Split','Block Glitch','Digital Tear','Zoom Blur','Edge Glow','Shockwave','Micro Shake'],
 transition:['Zoom In','Zoom Out','Punch Zoom','Elastic Zoom','Slide Left','Slide Right','Whip Up','Blur Cross','RGB Glitch','Quarter Spin','White Flash'],
 entrance:['Fade Rise','Zoom Reveal','Elastic Scale','Slide Focus','Bounce Open','Rotate Reveal','Glitch Arrival','Mask Reveal'],
 exit:['Fade Away','Zoom Collapse','Slide Depart','Elastic Exit','Rotate Away','Blur Dissolve','Signal Exit','Mask Close'],
 motion:['Pulse','Breathing','Micro Zoom','Impact Shake','Floating','Heartbeat','Jitter','Cinematic Push'],
 camera:['Smooth Zoom In','Smooth Zoom Out','Punch Camera','Snap Focus','Dolly Simulation','Beat Zoom','Diagonal Focus','Orbit Zoom'],
 text:['Letter Reveal','Word Reveal','Tracking Open','Type Impact','Social Pop','Cinematic Title','Glitch Letters','Minimal Fade'],
 color:['Cinematic Dark','Cold Night','Neon Blue','Golden Cinema','Hard Contrast','Clean 4K','Muted Film','Vintage Dark','Deep Black','Cyber Blue']
}
const CATEGORIES={effect:['Color','Light','Blur','Motion','Distortion','Glitch','RGB','Stylize','Noise','Lens','Warp','Sharpen','Cinematic','Retro'],transition:['Zoom','Slide','Whip','Blur','Glitch','Rotation','Scale','Light','Creative'],entrance:['Fade','Zoom','Scale','Slide','Bounce','Elastic','Rotate','Blur','Glitch','Light','Mask Reveal','Text Reveal','Cinematic','Impact'],exit:['Fade','Zoom','Slide','Collapse','Rotate','Blur','Glitch','Light','Mask','Impact','Cinematic'],motion:['Pulse','Shake','Float','Bounce','Drift','Cinematic'],camera:['Zoom','Punch','Dolly','Bounce','Anchor','Rotation'],text:['Fade','Slide','Scale','Bounce','Blur','Glitch','Letter Reveal','Word Reveal','Tracking','Rotation','Impact','Cinematic','Minimal','Social'],color:['Cinematic','Night','Film','Clean','Vintage','Cyber']}
const PRIMITIVES={effect:['color','blur','rgbOffset','noise','glow','distortion','transform'],transition:['transform','opacity','blur','rgbOffset','glow'],entrance:['transform','opacity'],exit:['transform','opacity'],motion:['transform'],camera:['transform','blur'],text:['transform','opacity','blur'],color:['color']}
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
const parameter=(id,value,min,max)=>({id,label:id[0].toUpperCase()+id.slice(1),value,min,max,keyframeable:true})
export function makeCatalog(kind,count=100){if(!TITLES[kind])throw new RangeError(`Unknown recipe kind: ${kind}`);return Array.from({length:count},(_,i)=>{const base=TITLES[kind][i%TITLES[kind].length],variant=Math.floor(i/TITLES[kind].length)+1,category=CATEGORIES[kind][i%CATEGORIES[kind].length],amount=20+(i*7)%75;return{id:`${kind}-${slug(base)}-${variant}`,kind,name:variant===1?base:`${base} ${variant}`,category,tags:[kind,category.toLowerCase(),...base.toLowerCase().split(' ')],duration:+(.25+(i%8)*.1).toFixed(2),primitives:PRIMITIVES[kind].slice(0,1+i%PRIMITIVES[kind].length),parameters:[parameter('amount',amount,0,100),parameter('mix',100,0,100)],keyframeRecipe:[{property:kind==='color'?'color.amount':kind==='effect'?'effect.amount':'transform.scale',at:0,value:kind==='exit'?100:0},{property:kind==='color'?'color.amount':kind==='effect'?'effect.amount':'transform.scale',at:1,value:kind==='exit'?0:100}],easing:['linear','ease-in','ease-out','ease-in-out'][i%4],previewDefinition:{type:category.toLowerCase().includes('glitch')?'glitch':kind==='transition'?'transition':kind==='text'?'text':'motion',hue:(i*37)%360},capabilityRequirements:[],status:i%17===0?'Experimental':'Ready'}})}
export const catalogs=Object.freeze(Object.fromEntries(Object.keys(TITLES).map(k=>[k,makeCatalog(k)])))
export const allRecipes=Object.freeze(Object.values(catalogs).flat())
export function validateParameters(recipe,values={}){const result={};for(const p of recipe.parameters){const n=Number(values[p.id]??p.value);if(!Number.isFinite(n))throw new TypeError(`${p.id} must be numeric`);result[p.id]=Math.min(p.max,Math.max(p.min,n))}return result}
export function applyRecipe(layer,recipe,values={}){if(!layer||!recipe)throw new TypeError('A layer and recipe are required');const params=validateParameters(recipe,values);if(recipe.kind==='effect'||recipe.kind==='color'){layer.effects??=[];layer.effects.push({id:`${recipe.id}-${Date.now()}`,recipeId:recipe.id,name:recipe.name,enabled:true,primitives:[...recipe.primitives],params,keyframes:{}})}else{layer.keyframes??={};for(const frame of recipe.keyframeRecipe){const key=frame.property.split('.').at(-1);(layer.keyframes[key]??=[]).push({time:(layer.start||0)+frame.at*recipe.duration,value:frame.value,interpolation:recipe.easing})}}return layer}
export function searchRecipes(query='',options={}){const q=query.trim().toLowerCase(),source=options.kind?catalogs[options.kind]:allRecipes;return source.filter(r=>(!options.category||r.category===options.category)&&(!q||[r.name,r.category,...r.tags].join(' ').toLowerCase().includes(q)))}
export function exportCapabilities(env=globalThis){const MR=env.MediaRecorder,types=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/mp4'];return{canvas:Boolean(env.HTMLCanvasElement),mediaRecorder:Boolean(MR),formats:MR?types.map(mime=>({mime,supported:Boolean(MR.isTypeSupported?.(mime))})):types.map(mime=>({mime,supported:false})),frameExport:Boolean(env.HTMLCanvasElement)}}
export class CreativePreferences{constructor(storage){this.storage=storage;this.favorites=new Set(JSON.parse(storage?.getItem('km-creative-favorites')||'[]'));this.recent=[]}toggle(id){this.favorites.has(id)?this.favorites.delete(id):this.favorites.add(id);this.storage?.setItem('km-creative-favorites',JSON.stringify([...this.favorites]));return this.favorites.has(id)}use(id){this.recent=[id,...this.recent.filter(x=>x!==id)].slice(0,24)}}
